export default {
    colors_milky: "#fffcf3",
    colors_black: "#000000",
    colors_darkSlateGray: "#b0e79e",
    colors_Aquamarine1: "#c6fbff",
    colors_DarkSeaGreen1: "#cfffbe",
    colors_skyblue: "#00a0e9",
    colors_chocolate: "#483a2b",
    colors_khaki: "#f5d47b",
    colors_turquoise: "#3a9be9",
    colors_darkCyan: "#4baf9f",
    colors_teal: "#14474a",
    colors_whileGray: "#f5f5f5",
    colors_SandyBrown: "#fbe097",
    colors_DarkSlateGray: "#5edac6",
    colors_opaqueBrown: "#949191",
    colors_pink: "#ff9bca",
    colors_DarkSeaGreen2: "#a8f7e5",
    colors_DarkSlateGray3: "#a8f7e5",
    colors_DarkSlateGray1: "#b5fff3",
    colors_orange: "#ff5858",
    colors_liner_gray_white: "#cef8f1",
    colors_item: "#b4eef4"
};

